INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(10088, 'Mouse', 'Mus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(10116, 'Rat', 'Rattus norvegicus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(112268, 'Mosquito', 'Anopheles minimus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(112509, 'Barley', 'Hordeum vulgare subsp. vulgare');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(139723, 'Mosquito', 'Anopheles culicifacies');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(199890, 'Mosquito', 'Anopheles epiroticus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(215358, 'Large yellow croaker', 'Larimichthys crocea');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(30066, 'Mosquito', 'Anopheles merus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(30069, 'Mosquito', 'Anopheles stephensi');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(30523, 'Cow', 'Bos taurus x Bos indicus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(34506, 'Rat threadworm', 'Strongyloides ratti');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(34690, 'Mosquito', 'Anopheles melas');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(34691, 'Mosquito', 'Anopheles quadriannulatus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(3702, 'Thale cress', 'Arabidopsis thaliana');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(3885, 'Common bean', 'Phaseolus vulgaris');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(39947, 'Rice', 'Oryza sativa Japonica Group');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(4081, 'Tomato', 'Solanum lycopersicum');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(4530, 'Rice', 'Oryza sativa');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(4557, 'Sorghum', 'Sorghum');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(4577, 'Maize', 'Zea mays');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(469796, 'Sheep', 'Ovis orientalis');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(4896, 'Fission yeast', 'Schizosaccharomyces pombe');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(59896, 'Sheep', 'Ovis vignei');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(60711, 'Vervet monkey', 'Chlorocebus sabaeus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(6183, 'Blood fluke', 'Schistosoma mansoni');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(62324, 'Mosquito', 'Anopheles funestus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(69004, 'Mosquito', 'Anopheles farauti');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(7159, 'Mosquito', 'Aedes aegypti');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(7165, 'Mosquito', 'Anopheles gambiae');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(7173, 'Mosquito', 'Anopheles arabiensis');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(74873, 'Mosquito', 'Anopheles sinensis');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(7955, 'Zebrafish', 'Danio rerio');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9606, 'Human', 'Homo sapiens');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9796, 'Horse', 'Equus caballus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9823, 'Pig', 'Sus scrofa');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9913, 'Cow', 'Bos taurus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9923, 'Goat', 'Capra aegagrus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9925, 'Goat', 'Capra hircus');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9935, 'Sheep', 'Ovis');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9938, 'Sheep', 'Ovis aries musimon');
INSERT INTO taxonomies(taxonomy_id, taxonomy_common_name, taxonomy_scientific_name) VALUES(9940, 'Sheep', 'Ovis aries');
